stages:
  - build
  - test

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: "1"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"

before_script:
  - export PATH="$PATH:/root/.dotnet/tools"

build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet restore
    - dotnet build --configuration Release --no-restore
  artifacts:
    paths:
      - '**/bin/Release/'
    expire_in: 1 week

test:
  stage: test
  image: mcr.microsoft.com/dotnet/sdk:8.0
  script:
    - dotnet test --configuration Release --no-build --logger "trx;LogFileName=test-results.trx"
  artifacts:
    when: always
    paths:
      - '**/TestResults/'
    expire_in: 1 week