name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 0 * * *' # Runs at 00:00 UTC every day
  workflow_dispatch:
    # inputs:
    #     browser:
    #       description: 'Browser to run tests against (chrome or edge)'
    #       required: true
    #       default: 'chrome'
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Run API Tests
      run: dotnet test --no-build --verbosity normal --filter "Category=API" --logger "trx;LogFileName=api_test_results.trx" --results-directory ./TestResults/API
      continue-on-error: true

    - name: Run UI Tests
      run: dotnet test --no-build --verbosity normal --filter "Category=UI" --logger "trx;LogFileName=ui_test_results.trx" --results-directory ./TestResults/UI
      continue-on-error: true

    - name: Upload API Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: API-Test-Results
        path: ./TestResults/API

    - name: Upload UI Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: UI-Test-Results
        path: ./TestResults/UI

    - name: Upload Screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Screenshots
        path: ./Tests/bin/Debug/net8.0/screenshots
        if-no-files-found: warn

    - name: Upload Logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: Logs
        path: ./Tests/bin/Debug/net8.0/logs
        if-no-files-found: warn
